config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :potential_customers
  resources :users
  resources :skillzers
  resources :projects

  get '/prelaunch' => 'potential_customers#new'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/potential_customer.rb
class PotentialCustomer < ActiveRecord::Base
  self.inheritance_column = nil
  validates :email, 
    presence: {message: "Please enter your email address."}, 
    uniqueness: {message: "You already signed up."}
  validates :type, 
    presence: {message: "Please indicate why you would join."}
  validates :description, 
    presence: {message: "Please describe why you would join."}
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  include AASM

  friendly_id :name, use: :slugged

  aasm do
    state :unstarted, initial: true
    state :started

    event :start do
      transitions from: :unstarted, to: :started
    end
  end

  has_many :project_skills
  has_many :skills, through: :project_skills

  has_attached_file :picture

  validates_attachment :picture, :content_type => { :content_type => "image/jpeg" }
end

app/models/project_skill.rb
class ProjectSkill < ActiveRecord::Base
  belongs_to :skill
  belongs_to :project
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :reviewable, polymorphic: true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :user_skills
  has_many :users, through: :user_skills
  has_many :project_skills
  has_many :projects, through: :project_skills

  has_attached_file :picture

  validates_attachment :picture,
    content_type: { content_type: ["image/jpeg", "image/png"] }
end

app/models/skill_seeker.rb
class SkillSeeker < User
end

app/models/skillzer.rb
class Skillzer < User
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  extend FriendlyId
  friendly_id :fullname, use: :slugged

  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skills, dependent: :destroy
  has_many :reviews, as: :reviewable

  has_attached_file :profile_picture

  validates_attachment :profile_picture, :content_type => { :content_type => "image/jpeg" }

  def fullname
    "#{first_name} #{last_name}"
  end

  def skillzer?
    type == 'Skillzer'
  end

  def skill_seeker?
    type == 'SkillSeeker'
  end
end

app/models/user_skill.rb
class UserSkill < ActiveRecord::Base
  has_many :reviews, as: :reviewable
  belongs_to :user
  belongs_to :skill
end

app/controllers/potential_customers_controller.rb
class PotentialCustomersController < ApplicationController
  def index
  end

  def new
    @potential_customer = PotentialCustomer.new
  end

  def create
    @potential_customer = PotentialCustomer.new(potential_customer_params)
    if @potential_customer.save
      render 'confirmation'
    else
      render 'new'
    end
  end

  def show
    @potential_customer = PotentialCustomer.find(params[:id])
  end

  private

  def potential_customer_params
    params.require(:potential_customer).permit(:email, :type, :description)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show]

  def index
    @projects = Project.all
  end

  def show
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
end

app/controllers/skillzers_controller.rb
class SkillzersController < ApplicationController
  respond_to :json, :html

  before_action :find_skillzer, only: :show

  def index
    @skillzers = Skillzer.all
    respond_with @skillzers
  end

  def show
    respond_with @skillzer
  end

  private

  def find_skillzer
    @skillzer = Skillzer.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]

  def show
  end

  private

  def find_user
    @user = User.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to user_path(current_user) if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user 
  end 
  
  def resource
    @resource ||= User.new 
  end 
  
  def devise_mapping 
    @devise_mapping ||= Devise.mappings[:user] 
  end 
  
  def resource_class
    User
  end
end

app/helpers/potential_customers_helper.rb
module PotentialCustomersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/skillzers_helper.rb
module SkillzersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/potential_customers/confirmation.html.haml
%div{:class=>'container box'}
  %h2
    YOU ROCK!
  %p
    Thank you for your interest. We'll be in touch when our website is closer to launch. Congrats on being early adopters to a new way of connecting skills with businesses. YOU ROCK!

app/views/potential_customers/index.html.haml
%h1 PotentialCustomers#index
%p Find me in app/views/potential_customers/index.html.haml

app/views/potential_customers/new.html.haml
%div{:class=>'container'}
  %h1
    Do what you love, let your passion drive business.  
  
  %div{:class=>'col-sm-3'}
    %span
      %strong
        How do I join?
      Just add your email to the pre-launch list and we'll reach out to you closer to launch.
	
    -if @potential_customer.errors.any?
      %ul{:class=>'error'} 
        -@potential_customer.errors.each do |attr,msg|
          %li
            =msg


    = form_for(:potential_customer, url: potential_customers_path ) do |f| 
      = devise_error_messages!
      .form-group
        = f.label :type, 'I would join this site because '
        = f.select :type, [['----', nil],['I have skills','employee'],['I am seeking skills','employer'],['I have & I am seeking skills','both']]
      .form-group
        .input-group
          = f.label :email
          = f.email_field :email, class: 'form-control', :placeholder=> 'Email'
      .form-group
        .input-group
          = f.label :description
          = f.text_area :description, class: 'form-control', :rows=> 8, :placeholder=>'Describe your skill and/or business.'
      = f.submit "Interested!", class: 'btn side-skillz-btn'
      
  %section{:class=>'box col-sm-4'}
    %h2
      Has Skills
    %p
      Whether you love writing, photography, cooking or programming we aim to match you with business seeking your skills. We pay at a steading increasing rate until you reach our highest rank. After you have proven yourself, we open the door to in-depth work with our community.
      %br
      %br
      %strong
        Why Join?
      Work in what you love doing. We don't care what your day job is.
      %br
      %br
      %strong
        What do I get out of it?
      You get connected to business that are looking for talented people like you. You have the opportunity to build your portfolio while improving your skills.


  %section{:class=>'box col-sm-4'}
    %h2
      Seeking Skills
    %p
      As a business owner you are often looking for talented people but you have difficulty finding the right fit. SideSkillz provides you with vetted candidates who love and are talented in a particular skill. You can leverage their passion to build your business and help them succeed.
      %br
      %br
      %strong
        Why Join?
      We hook you up with people who can boost your business as they build their skills.
      %br
      %br
      %strong
        What do I get out of it?
      We vet our candidate for competence and motivation. Candidate performance their service well below market rates.Ultimately you choose which candidates you want to hire and whether or not you want to keep working with them.

app/views/potential_customers/show.html.haml
%div
  %h3
    Thank you for your interest.
%div
  %h4 Your Details
  %p Email: #{@potential_customer.email}
  %p Interest: #{@potential_customer.type}
  %p Description: #{@potential_customer.description}