config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :potential_customers
  resources :users
  resources :skillzers
  resources :projects

  get '/prelaunch' => 'potential_customers#new'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/potential_customer.rb
class PotentialCustomer < ActiveRecord::Base
  self.inheritance_column = nil
  validates :email, 
    presence: {message: "Please enter your email address."}, 
    uniqueness: {message: "You already signed up."}
  validates :type, 
    presence: {message: "Please indicate why you would join."}
  validates :description, 
    presence: {message: "Please describe why you would join."}
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  include AASM

  friendly_id :name, use: :slugged

  aasm do
    state :unstarted, initial: true
    state :started

    event :start do
      transitions from: :unstarted, to: :started
    end
  end

  has_many :project_skills
  has_many :skills, through: :project_skills

  has_attached_file :picture

  validates_attachment :picture, :content_type => { :content_type => "image/jpeg" }
end

app/models/project_skill.rb
class ProjectSkill < ActiveRecord::Base
  belongs_to :skill
  belongs_to :project
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :reviewable, polymorphic: true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :user_skills
  has_many :users, through: :user_skills
  has_many :project_skills
  has_many :projects, through: :project_skills

  has_attached_file :picture

  validates_attachment :picture,
    content_type: { content_type: ["image/jpeg", "image/png"] }
end

app/models/skill_seeker.rb
class SkillSeeker < User
end

app/models/skillzer.rb
class Skillzer < User
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  extend FriendlyId
  friendly_id :fullname, use: :slugged

  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skills, dependent: :destroy
  has_many :reviews, as: :reviewable

  has_attached_file :profile_picture

  validates_attachment :profile_picture, :content_type => { :content_type => "image/jpeg" }

  def fullname
    "#{first_name} #{last_name}"
  end

  def skillzer?
    type == 'Skillzer'
  end

  def skill_seeker?
    type == 'SkillSeeker'
  end
end

app/models/user_skill.rb
class UserSkill < ActiveRecord::Base
  has_many :reviews, as: :reviewable
  belongs_to :user
  belongs_to :skill
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :type
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
    devise_parameter_sanitizer.for(:sign_up) << :company_name
    devise_parameter_sanitizer.for(:sign_up) << :profile_picture
    devise_parameter_sanitizer.for(:account_update) << :type
    devise_parameter_sanitizer.for(:account_update) << :first_name
    devise_parameter_sanitizer.for(:account_update) << :last_name
    devise_parameter_sanitizer.for(:account_update) << :company_name
    devise_parameter_sanitizer.for(:account_update) << :profile_picture
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show]

  def index
    @projects = Project.all
  end

  def show
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
end

app/controllers/skillzers_controller.rb
class SkillzersController < ApplicationController
  respond_to :json, :html

  before_action :find_skillzer, only: :show

  def index
    @skillzers = Skillzer.all
    respond_with @skillzers
  end

  def show
    respond_with @skillzer
  end

  private

  def find_skillzer
    @skillzer = Skillzer.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]

  def show
  end

  private

  def find_user
    @user = User.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to user_path(current_user) if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user 
  end 
  
  def resource
    @resource ||= User.new 
  end 
  
  def devise_mapping 
    @devise_mapping ||= Devise.mappings[:user] 
  end 
  
  def resource_class
    User
  end
end

app/helpers/potential_customers_helper.rb
module PotentialCustomersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/skillzers_helper.rb
module SkillzersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/projects/_card.html.haml
%li
  = link_to project_path(project) do
    .project-card
      %h3= project.name

app/views/projects/_project_background_info.html.haml
.project-profile-picture-section
  .container
    .row
      .col-sm-12.text-center
        %h1= @project.name

app/views/projects/index.html.haml
.container
  .row
    .col-sm-12.text-center
      %ul.list-inline.list-unstyled
        - @projects.each do |project|
          = render partial: 'card', locals: { project: project }

app/views/projects/show.html.haml
.project-description-section
  .container
    .row
      .col-sm-6
        %h1 Project Description
        %p= @project.description
        %ul.list-inline.list-unstyled
          %li.project-status-duration.text-center= "#{@project.duration} days"
          %li.project-status-duration.text-center= @project.aasm_state
      .col-sm-6
        %h1 Skillz Needed
        %ul.list-inline.list-unstyled
          - @project.skills.each do |skill|
            = render partial: 'skills/card', locals: { skill: skill }

.project-available-skillzers-section
  .container
    .row
      .col-sm-12
        %h1 Available SkillZers
        %ul.list-unstyled.list-inline
          - @project.skills.map(&:users).flatten.uniq.each do |user|
            = render partial: 'users/card', locals: { user: user }

app/views/skills/_card.html.haml
%li.skill-card.text-center
  = image_tag skill.picture.url, class: 'skill-picture'
  %h4= skill.name

app/views/skillzers/index.html.haml
.container{ ng: { controller: 'skillzersCtrl' } }
  %p{ ng: { repeat: 'skillzer in skillzers' } }
    {{skillzer[0].first_name}}

app/views/users/_card.html.haml
%li
  .user-card
    .text-center
      - if user.profile_picture.blank?
        = image_tag 'missing.png', width: '120',
          class: 'img-responsive img-circle profile-picture'
      - else
        = image_tag user.profile_picture.url, width: '120', 
          class: 'img-responsive img-circle profile-picture'
      %h3= user.fullname
      - skill = user.skills.sample
      %p= skill.name
      .star{ data: { rating: user.reviews.map(&:rating).inject(:+) } }
      %p= "#{user.reviews.count} reviews"
      .solid-grey-line
      %ul.list-unstyled.list-inline
        %li= link_to 'Message', root_path, class: 'user-action-link'
        %li= link_to 'Hire', root_path, class: 'user-action-link'

app/views/users/_user_background_info.html.haml
- @user ||= current_user
.user-profile-picture-section
  .container
    .row
      .col-sm-12.text-center
        - if @user.profile_picture.blank?
          = image_tag 'missing.png', width: '200',
            class: 'img-responsive img-circle profile-picture'
        - else
          = image_tag @user.profile_picture.url, width: '200', 
            class: 'img-responsive img-circle profile-picture'
        %h1= @user.fullname

app/views/users/show.html.haml
.side-skillz-section
  .container
    .row
      .col-sm-12.text-center
        %h1 Side SkillZ
        %ul.list-inline.list-unstyled.user-skill-list
          - @user.user_skills.each do |user_skill|
            %li.user-skill-list
              %h3= user_skill.skill.name
              .star{ data: { rating: user_skill.rating } }

.container
  .dotted-red-line

.recommended-projects-section
  .container
    .row
      .col-sm-12.text-center
        %h1 Recommended Projects
        %ul.list-inline.list-unstyled
          - Project.all.each do |project|
            = render partial: 'projects/card', locals: { project: project }