config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :potential_customers
  resources :users
  resources :skillzers
  resources :projects

  get '/prelaunch' => 'potential_customers#new'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/potential_customer.rb
class PotentialCustomer < ActiveRecord::Base
  self.inheritance_column = nil
  validates :email, 
    presence: {message: "Please enter your email address."}, 
    uniqueness: {message: "You already signed up."}
  validates :type, 
    presence: {message: "Please indicate why you would join."}
  validates :description, 
    presence: {message: "Please describe why you would join."}
end

app/models/project.rb
class Project < ActiveRecord::Base
  extend FriendlyId
  include AASM

  friendly_id :name, use: :slugged

  aasm do
    state :unstarted, initial: true
    state :started

    event :start do
      transitions from: :unstarted, to: :started
    end
  end

  has_many :project_skills
  has_many :skills, through: :project_skills

  has_attached_file :picture

  validates_attachment :picture, :content_type => { :content_type => "image/jpeg" }
end

app/models/project_skill.rb
class ProjectSkill < ActiveRecord::Base
  belongs_to :skill
  belongs_to :project
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :reviewable, polymorphic: true
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  has_many :user_skills
  has_many :users, through: :user_skills
  has_many :project_skills
  has_many :projects, through: :project_skills

  has_attached_file :picture

  validates_attachment :picture,
    content_type: { content_type: ["image/jpeg", "image/png"] }
end

app/models/skill_seeker.rb
class SkillSeeker < User
end

app/models/skillzer.rb
class Skillzer < User
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  extend FriendlyId
  friendly_id :fullname, use: :slugged

  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skills, dependent: :destroy
  has_many :reviews, as: :reviewable

  has_attached_file :profile_picture

  validates_attachment :profile_picture, :content_type => { :content_type => "image/jpeg" }

  def fullname
    "#{first_name} #{last_name}"
  end

  def skillzer?
    type == 'Skillzer'
  end

  def skill_seeker?
    type == 'SkillSeeker'
  end
end

app/models/user_skill.rb
class UserSkill < ActiveRecord::Base
  has_many :reviews, as: :reviewable
  belongs_to :user
  belongs_to :skill
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show]

  def index
    @projects = Project.all
  end

  def show
  end

  private

  def find_project
    @project = Project.friendly.find(params[:id])
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show]

  def show
  end

  private

  def find_user
    @user = User.friendly.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to user_path(current_user) if user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user 
  end 
  
  def resource
    @resource ||= User.new 
  end 
  
  def devise_mapping 
    @devise_mapping ||= Devise.mappings[:user] 
  end 
  
  def resource_class
    User
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/skillzers_helper.rb
module SkillzersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.haml
- unless flash.blank?
  - flash.each do |flash_type, flash_message|
    .container#notification-bar
      .row
        .col-sm-12
          %div{ class: "alert alert-#{flash_type == "notice" ? "success" : "danger"} text-center" }
            %button{ type: 'button', class: :close, data: { dismiss: :alert} }x
            = flash_message

app/views/layouts/_footer.html.haml
%footer
  .container
    .row
      .col-sm-12.text-center.copyright
        Copyright 2014 Side Skillz
    .row
      .col-sm-12.text-center
        %ul.list-unstyled.list-inline
          %li= link_to 'About Us', '#'
          %li= link_to 'Private Policy', '#'
          %li= link_to 'Terms & Conditions', '#'
          %li= link_to 'Fees & Charges', '#'

app/views/layouts/_header.html.haml
- if current_user.skill_seeker?
  = render 'layouts/skill_seeker_header'
- else
  = render 'layouts/skillzer_header'

app/views/layouts/_skill_seeker_header.html.haml
.signed-in-index
  %header
    %nav.navbar.navbar-default{ role: 'navigation' }
      .container
        .navbar-header
          %button.navbar-toggle{ data: { target: '#header-navbar-collapse',
            toggle: 'collapse' }, type: 'button' }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to root_path, class: 'navbar-brand' do
            %ul.list-inline.list-unstyled
              %li= image_tag 'logo_white.png', width: '60'
              %li Side Skillz
        .navbar-collapse.collapse#header-navbar-collapse{ role: 'navigation' }
          %ul.nav.navbar-nav.navbar-left.navbar-main-links
            %li= link_to 'Profile', user_path(current_user)
            %li= link_to 'Skillzers', skillzers_path
            %li= link_to 'Inbox', '#'
            %li= link_to 'Settings', '#'
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/layouts/_skillzer_header.html.haml
.signed-in-index
  %header
    %nav.navbar.navbar-default{ role: 'navigation' }
      .container
        .navbar-header
          %button.navbar-toggle{ data: { target: '#header-navbar-collapse',
            toggle: 'collapse' }, type: 'button' }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to root_path, class: 'navbar-brand' do
            %ul.list-inline.list-unstyled
              %li= image_tag 'logo_white.png', width: '60'
              %li Side Skillz
        .navbar-collapse.collapse#header-navbar-collapse{ role: 'navigation' }
          %ul.nav.navbar-nav.navbar-left.navbar-main-links
            %li= link_to 'Profile', user_path(current_user)
            %li= link_to 'Projects', projects_path
            %li= link_to 'Inbox', '#'
            %li= link_to 'Settings', '#'
          %ul.nav.navbar-nav.navbar-right
            %li= link_to 'Sign out', destroy_user_session_path, method: :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SideSkillz
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
  %body{ 'ng-app' => 'sideSkillz' }
    - if user_signed_in?
      = render 'layouts/header'
      = render 'layouts/flash'
      - if controller_name == 'users'
        = render 'users/user_background_info'
      - if controller_name == 'projects' && action_name == 'show'
        = render 'projects/project_background_info'
      = yield
      = render 'layouts/footer'
    - elsif controller_name == 'potential_customers'
      = yield
    - else
      - if controller_name == 'welcome' && action_name == 'index'
        = render 'layouts/flash'
        = yield
      - else
        = render 'layouts/header'
        = render 'layouts/footer'
        = yield